codecov: true
coveralls: true
language: python
python:
  - '3.9'

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

install:
  - pip install safety
  - pip install psycopg2
  - pip install pytest
  - pip install fastapi["all"]


before_script: 
  - pip install docker-compose
  - cd /home/travis/build/nojoven/CommentsGate/
script:
  - docker-compose --env-file ./config/.env up -d --build
  - pwd
  - ls -a
  - safety check
  - pytest
