codecov: true
coveralls: true
language: python
python:
  - '3.9'

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

install:
  - pip install safety
  - pip install psycopg2
  - pip install pytest
  - pip install fastapi["all"]
  - pip install sqlalchemy


before_script: 
  - pip install docker-compose
  - pwd
  - cd /home/travis/build/nojoven/CommentsGate/
script:
  - docker-compose --env-file ./config/.env up -d --build
  - pip install --no-cache-dir --upgrade -r /CommentsGate/requirements.txt
  - pwd
  - ls -a
  - safety check
  - pytest
