codecov: true
coveralls: true
language: python
python:
  - '3.9'

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

install:
  - pip install safety
  - pip install psycopg2


before_script: pip install docker-compose

script:
  - safety check
  - docker-compose docker-compose --env-file ./config/.env up --build sh -c "pytest && flake8"
